#!/usr/bin/env python
#############################################################################
#                                                                           #
#    Nagios custom plugins -- A python library and a set of Nagios plugins. #
#    Copyright (C) 2010  Revolution Linux, inc. <info@revolutionlinux.com>  #
#                                                                           #
#    This program is free software: you can redistribute it and/or modify   #
#    it under the terms of the GNU General Public License as published by   #
#    the Free Software Foundation, either version 3 of the License, or      #
#    (at your option) any later version.                                    #
#                                                                           #
#    This program is distributed in the hope that it will be useful,        #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of         #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          #
#    GNU General Public License for more details.                           #
#                                                                           #
#    You should have received a copy of the GNU General Public License      #
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.  #
#                                                                           #
#############################################################################
import re, subprocess
from optparse import Option
try:
    import utils as nagios
except ImportError:
    import sys
    print >> sys.stderr, __file__, ": Cannot use the Nagios library. Exiting"
    sys.exit(100)

lifeline = re.compile(r"(\d) received")

def ping_host(options, args):
    if len(args) == 0:
        raise nagios.ExecutionUnknown("No host IP given on the command line")

    host_ip = args[0]
    nagios.nagios_debug("PING: Host IP: %s" % host_ip)
    nagios.nagios_debug("PING: Sending %d packets" % options.ping_count)

    ping = subprocess.Popen(
        ["ping", "-q", "-c%d" % options.ping_count, host_ip],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    pingaling = ping.stdout

    for line in pingaling.readlines():
        # Verbose output, cut superfluous \n characters
        print line[:-1]

        igot = re.findall(lifeline,line)
        if igot and int(igot[0]) != options.ping_count:
            raise nagios.ExecutionCritical("No response from host %s" % host_ip)

    if ping.wait() != 0:
        err = ping.stderr.readline()
        raise nagios.ExecutionUnknown("Execution failed: %s" % err[:-1])

    return "Host is up"

if __name__ == '__main__':
    check_ping = nagios.Check(
        func=ping_host,
        name="PING",
        extended_usage_text="<IP address>"
    )
    check_ping.add_option(Option(
        "-c", type="int", default=4, dest="ping_count",
        help="Number of ICMP Ping packets that will be sent"
    ) )
    check_ping.run()

